"""Portfolio report aggregation (08-feature-spec-collaboration.md §7).

Pure query + aggregation functions shared by the report pipeline and the
frontend's live dashboard. No LLM involvement — these reports are
deterministic aggregations over stored analysis data.
"""
from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.models import Document, DocumentStatus, Obligation, Risk

SCORE_BUCKETS = [(0, 39), (40, 59), (60, 79), (80, 100)]

SEVERITY_ORDER = ["critical", "high", "medium", "low"]


def _bucket_label(low: int, high: int) -> str:
    if high == 100:
        return f"{low}-100"
    return f"{low}-{high}"


async def _load_documents(
    session: AsyncSession,
    organization_id: UUID,
    document_ids: list[UUID] | None,
) -> list[Document]:
    """Analysis-ready documents in scope, oldest first (stable report ordering)."""
    stmt = select(Document).where(
        Document.organization_id == organization_id,
        Document.status == DocumentStatus.ANALYSIS_READY,
    )
    if document_ids:
        stmt = stmt.where(Document.id.in_(document_ids))
    stmt = stmt.order_by(Document.created_at)
    result = await session.execute(stmt)
    return list(result.scalars().all())


async def build_portfolio_risk_data(
    session: AsyncSession,
    *,
    organization_id: UUID,
    document_ids: list[UUID] | None = None,
    now: datetime | None = None,
) -> dict:
    """Aggregate risk and score data across the document scope."""
    now = now or datetime.now(UTC)
    documents = await _load_documents(session, organization_id, document_ids)
    doc_by_id = {doc.id: doc for doc in documents}
    scope_ids = list(doc_by_id)

    risks: list[Risk] = []
    if scope_ids:
        result = await session.execute(
            select(Risk)
            .where(Risk.document_id.in_(scope_ids))
            .order_by(Risk.document_id)
        )
        risks = list(result.scalars().all())

    risks_by_severity = {sev: 0 for sev in SEVERITY_ORDER}
    risks_by_type: dict[str, int] = {}
    critical_documents: dict[UUID, list[dict]] = {}
    for risk in risks:
        sev = risk.severity.value if hasattr(risk.severity, "value") else str(risk.severity)
        rtype = risk.risk_type.value if hasattr(risk.risk_type, "value") else str(risk.risk_type)
        risks_by_severity[sev] = risks_by_severity.get(sev, 0) + 1
        risks_by_type[rtype] = risks_by_type.get(rtype, 0) + 1
        if sev == "critical":
            critical_documents.setdefault(risk.document_id, []).append(
                {
                    "risk_type": rtype,
                    "description": risk.description,
                    "page_number": risk.page_number,
                }
            )

    scores = [float(doc.contract_score) for doc in documents if doc.contract_score is not None]
    score_distribution = {
        _bucket_label(low, high): 0 for low, high in SCORE_BUCKETS
    }
    for score in scores:
        for low, high in SCORE_BUCKETS:
            if low <= score <= high:
                score_distribution[_bucket_label(low, high)] += 1
                break

    return {
        "report_type": "portfolio_risk",
        "generated_at": now.isoformat(),
        "scope": {
            "document_ids": [str(doc.id) for doc in documents],
            "document_count": len(documents),
            "filtered": bool(document_ids),
        },
        "summary": {
            "documents_analyzed": len(documents),
            "total_risks": len(risks),
            "critical_risk_count": risks_by_severity.get("critical", 0),
            "documents_with_critical_risks": len(critical_documents),
            "average_contract_score": round(sum(scores) / len(scores), 1) if scores else None,
        },
        "risks_by_severity": risks_by_severity,
        "risks_by_type": dict(sorted(risks_by_type.items(), key=lambda kv: -kv[1])),
        "score_distribution": score_distribution,
        "documents": [
            {
                "document_id": str(doc.id),
                "filename": doc.filename,
                "document_type": doc.document_type.value
                if hasattr(doc.document_type, "value")
                else str(doc.document_type),
                "contract_score": float(doc.contract_score) if doc.contract_score is not None else None,
                "risk_count": sum(
                    1 for r in risks if r.document_id == doc.id
                ),
                "critical_risks": critical_documents.get(doc.id, []),
            }
            for doc in documents
        ],
        "disclaimer": (
            "This report is generated by an automated document analysis tool "
            "and does not constitute legal advice. All findings must be "
            "reviewed by qualified legal professionals."
        ),
    }


async def build_obligation_calendar_data(
    session: AsyncSession,
    *,
    organization_id: UUID,
    document_ids: list[UUID] | None = None,
    now: datetime | None = None,
) -> dict:
    """All obligations across the document scope, bucketed for compliance tracking."""
    now = now or datetime.now(UTC)
    documents = await _load_documents(session, organization_id, document_ids)
    doc_by_id = {doc.id: doc for doc in documents}

    obligations: list[Obligation] = []
    if doc_by_id:
        result = await session.execute(
            select(Obligation)
            .where(Obligation.document_id.in_(list(doc_by_id)))
            .order_by(Obligation.deadline_date)
        )
        obligations = list(result.scalars().all())

    def to_entry(ob: Obligation) -> dict:
        doc = doc_by_id[ob.document_id]
        return {
            "document_id": str(ob.document_id),
            "filename": doc.filename,
            "obligated_party": ob.obligated_party,
            "description": ob.description,
            "deadline_date": ob.deadline_date.isoformat() if ob.deadline_date else None,
            "deadline_type": ob.deadline_type.value
            if hasattr(ob.deadline_type, "value")
            else str(ob.deadline_type),
            "status": ob.status.value if hasattr(ob.status, "value") else str(ob.status),
            "page_number": ob.page_number,
        }

    overdue = []
    due_soon = []
    upcoming = []
    no_deadline = []
    completed = []
    for ob in obligations:
        entry = to_entry(ob)
        status = entry["status"]
        if status == "completed":
            completed.append(entry)
        elif ob.deadline_date is None:
            no_deadline.append(entry)
        elif ob.deadline_date < now:
            overdue.append(entry)
        elif status == "overdue":
            overdue.append(entry)
        elif status == "due_soon":
            due_soon.append(entry)
        else:
            upcoming.append(entry)

    return {
        "report_type": "obligation_calendar",
        "generated_at": now.isoformat(),
        "scope": {
            "document_ids": [str(doc.id) for doc in documents],
            "document_count": len(documents),
            "filtered": bool(document_ids),
        },
        "summary": {
            "documents_analyzed": len(documents),
            "total_obligations": len(obligations),
            "overdue": len(overdue),
            "due_soon": len(due_soon),
            "upcoming": len(upcoming),
            "no_deadline": len(no_deadline),
            "completed": len(completed),
        },
        "overdue": overdue,
        "due_soon": due_soon,
        "upcoming": upcoming,
        "no_deadline": no_deadline,
        "completed": completed,
        "disclaimer": (
            "This report is generated by an automated document analysis tool "
            "and does not constitute legal advice. All findings must be "
            "reviewed by qualified legal professionals."
        ),
    }
